---
- name: Install Nginx server if planned
  apt:
    name: nginx
    state: latest
    update_cache: true
  when: install_nginx_var

- name: Get kernal and os type if Ubuntu 20+
  debug:
    msg:
      - "{{ ansible_facts['kernel_version'] }}"
      - "{{ ansible_facts['os_family'] }}"
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] | int >= "20"
  # when: (ansible_distribution=="Ubuntu") and (ansible_distribution_version is version('22.0','>='))
  # when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('22.0', '>=')

- name: Read file
  command: cat /etc/os-release
  register: file_content

- name: Check file and display content
  debug:
    var: file_content.stdout                                # https://docs.ansible.com/projects/ansible/latest/reference_appendices/common_return_values.html
    # var: file_content.stdout_lines                        # 'stdout' and 'stdout_lines' are return values available in ansible
    # var: file_content.stdout_lines[0:4]
    # msg: "{{ file_content.stdout_lines | select('search', '^PRETTY_NAME=') | first }}"
  # when: file_content is successful
  # when: "'PRETTY_NAME=' in file_content.stdout"           # https://docs.ansible.com/projects/rulebook/en/latest/conditions.html#supported-operators
  # when: "'PRETTY_NAME=' is in (file_content.stdout)"      # https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_tests.html#tests
  # when: file_content.stdout is search ("PRETTY_NAME=")    # 'in', 'is in' and 'is search' are test plugins within ansible.builtin.
  when: file_content.stdout.find('PRETTY_NAME') != -1       # https://www.w3schools.com/python/python_ref_string.asp
  # when: file_content.stdout.startswith('PRETTY_NAME')     # find() and startswith() are python string operators
  # when: file_content.stdout_lines | select('search', '^PRETTY_NAME=') | list | length > 0
                           # stdout_lines splits the multi-line stdout into a list where each line is an element
                           # select(test, arg1, arg2) filters stdout_lines by running any test on each element and selects only those that pass
                           # select('search', '^PRETTY_NAME=') runs ansible.buildtin.search on each list element selecting those that start with 'PRETTY_NAME'
                           # list filter is applied to control the data type. The subsequent filter checks if list is not empty.

- name: Loop through list when condition is true
  loop: "{{ list_var }}"
  debug:
    msg: "List Loop counter : {{ item }}"                   # item a keyword used when referring to elements of a loop
  when: list_var > 0

- name: Loop through dictionary when condition is true
  loop: "{{ dictionary_var | dict2items }}"                 # dict2items filter converts each key:value pair into list elements
  loop_control:
    loop_var: unit                                          # loop_var allows us to customise the looping keyword to not be 'item'
  debug:
    msg: "Dict key is {{ unit.key }} and value is {{ unit.value }}"
  when: unit.value > 0

- name: Loop through list of dictionary items
  debug:
    msg: "Name is {{ index.name }} and Number is {{ index.number }}"
  loop: "{{ list_of_dictionary_var }}"
  loop_control:
    loop_var: index
  when: index.number > 0
